### ISSUE TITLE
Psychedelicraft shaders not compatible with shader mod

### ISSUE THREAD

**Issue by lightning02** [Ivorforce/Psychedelicraft#29]
Hello, I made a bunch of test before write an issue here this time.. On 2 different graphic card (2 different computers), with only Psychedelicraft-1.5.2.jar + ivToolkit 1.2.1 installed and with ShadermodCore ShadersModCore-v2.3.31-mc1.7.10-f
Tests have been done on latest forge 1614(1.7.10)
The results are the same, a massive console spam of  "[B#347]  GL error 0x0502: Invalid operation at pre-useProgram".
Could you take a look into it? Should I reffer this issue to shadermod developers too?

This is what I see in the console and the fml latest log too;
http://pastebin.com/YvQvav7T
http://pastebin.com/xYFh4jp2

**Comment by Ivorforce** [comment]
Shaders are inherently incompatible. There can never be a fix for other shader mods working alongside Psychedelicraft. Best you can achieve is turning off 3D shaders.

**Comment by lightning02** [comment]
Honestly.. the real part that is bad to lose is the "after-water" effect that displays on your screen.. is really nothing that can be done about that? 
The only thing I see in the config file is the 2D shader option to disable, and this besides kill the purpose of the mod itself also disable the pretty after-water effect on your monitor :(

**Comment by Ivorforce** [comment]
The shaderEnabled option is the one to deactivate. The water droplets do work without it... I think. I did a good amount of work to ensure 2D shaders are capable of handling a majority of the effects too.

**Comment by lightning02** [comment]
Ok, I tested it just now, I thought that shaders = false was to disable entirely everything, instead, that option was the "3d shaders" you was talking about, and yes, in effect with 2d shader that pretty water effect at least remain :)

**Comment by Xray1716** [comment]
my friend and I tried to install this mod on 1.7.10. but the textures don't work because of it. they broke down. we don't have shaders, standard vanilla Minecraft. But the mod still doesn't work. what to do, please help me 🥺
