### ISSUE TITLE
Bedrock Port

### ISSUE THREAD

**Issue by Davis8483** [Ivorforce/Psychedelicraft#45]
I made a bedrock port of this addon,
[Psychedelicraft Bedrock Addon](https://github.com/Davis8483/Psychedelicraft-Bedrock-Addon)

**Comment by Ivorforce** [comment]
Hi, that's very interesting! Thanks for letting me know. Do you plan on uploading it anywhere?
Also, I'm guessing the port is largely content based and does not run any shaders, correct?

It may be beneficial if you joined me on my [discord channel](https://discord.gg/mt7uwQ4) :)

**Comment by Davis8483** [comment]
I did try uploading it to mcpdl, it was sadly denied,
![image](https://github.com/Ivorforce/Psychedelicraft/assets/76828148/1d9ea5d4-dcdd-4dfc-b28f-64c9ceb6f03d)

Shaders are unfortunately not possible on bedrock, so instead I used potion and sound effects. I currently have Cocaine and Cannabis added to the addon. Hopefully more to come later when I have time to work on it.

**Comment by Ivorforce** [comment]
I had the same issue on curseforge once - although they later re-accepted it when I described it more vaguely in the description, and openly rejected the real-life recreation.
Anyway, good luck, and thanks for letting me know! If you want input or discuss anything else, again feel free to drop by discord.
Cheers!

**Comment by aSushiLegend** [comment]
The mod hasn't been updated. I would appreciate an update or different port of the mod
