### ISSUE TITLE
[Request] move "crop<Name>" ore dict tags from the block to the fruit

### ISSUE THREAD

**Issue by InfinityRaider** [Ivorforce/Psychedelicraft#6]
Hello, I am the mod dev of AgriCraft, and I would like to have compatibility with your mod. For this I would request of you to follow the ore dict standard for crops. This is registering your seed as "seed<Name>" and the fruit/product of your crop as "crop<Name>". This makes it easier for me to support more mods.
I'm not the only one using this standard, the COFH Team is using this for their hydroponic farming machine as well.

Thanks

**Comment by Ivorforce** [comment]
Yo,

I have my OreDict constants all stored at https://github.com/Ivorforce/Psychedelicraft/blob/master/src/main/java/ivorius/psychedelicraft/crafting/OreDictionaryConstants.java - as you can see, I'm, for the most part, following the principle. The exclusions usually involve a more complex structure, like cannabis - the leaf is not really the 'fruit' of the plant, and neither are the buds really, so there I opted for unique names.

As for the common names, I tried to stick to what I found here: 
http://www.minecraftforge.net/wiki/Common_Oredict_names

Are there any specific changes you'd like to see? I took a quick look at your repo if there are any overlaps where I'd need to adjust my oredict names, but there don't seem to be any.

**Comment by InfinityRaider** [comment]
Well right now you are oredicting the crop blocks while it should be the fruits. Your tags are correct, but you are tagging the wrong objects. the "cropCannabis" tag should be on the cannabis leaves and teh buds instead of the block. Because if everything goes right, the player never actually aquires the block of the crop.

**Comment by Ivorforce** [comment]
I see. Yep, that makes sense.
I've made a commit that should hopefully address this. Is this to your liking? :)

**Comment by InfinityRaider** [comment]
Perfect, thanks
