### ISSUE TITLE
Can't fully turn off shaders

### ISSUE THREAD

**Issue by ultrasn0w** [Ivorforce/Psychedelicraft#7]
Hey Ivorforce,
Because some friends do not have a potato GPU, they were experiencing heavy FPS drops when looking towards the sky / seeing shader effects.
So I told them to disable the shaders in the config, however after I've done some testing on my own, we found out that even with this configuration, the shaders are still enabled:
```
visual {
    B:biomeHeatDistortion=false
    B:bypassPingPongBuffer=false
    D:digitalEffectPixelRescaleX=0.05000000074505806
    D:digitalEffectPixelRescaleY=0.05000000074505806
    B:disableDepthBuffer=true

    # The strength of DoF blur away from the player.
    D:dofFocalBlurFar=0.0

    # The strength of DoF blur towards the player.
    D:dofFocalBlurNear=0.0

    # The point at which DoF starts blurring the screen, away from the player, in blocks.
    D:dofFocalPointFar=512.0

    # The point at which DoF starts blurring the screen, towards the player, in blocks.
    D:dofFocalPointNear=0.0
    B:hurtOverlayEnabled=true
    B:motionBlur=false

    # If a fake skybox should be rendered to make shaders affect the fog line.
    B:renderFakeSkybox=true
    B:shader2DEnabled=false
    B:shaderEnabled=false
    D:sunFlareIntensity=0.28
    B:waterDistortion=false
    B:waterOverlayEnabled=false
}
```
Screenshot with this config: https://i.imgur.com/dV7QcAh.jpg
(the clouds are from another mod, ignore these)

Me as a owner of a fairly powerful GPU did not even recognize this bug, thanks to the potatoes! :)

**Comment by Ivorforce** [comment]
No worries - that's not even a shader, it's just a bit of plain OGL magic. It won't have noticeable impact on the performance, but you can still disable it by setting sunFlareIntensity=0.0 :)

**Comment by ultrasn0w** [comment]
Thank you for the immediate reply, I will pass this information to them and report back.

**Comment by ultrasn0w** [comment]
Interestingly the FPS seem to be better than before, guess I won't tell them that this should not have had any impact on that ^^
