### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by oaksvirals** [Ivorforce/Psychedelicraft#8]
I'm running a hub that connects multiple modpacks with portals to their perspective packs.

2 of the Packs have Psychedelicraft and they can't see the chat in the lobby since the lobby doesn't have Psychedelicraft. Is there anyway to fix this?

**Comment by Ivorforce** [comment]
I'm not sure what could cause this... for now I have added an option to the config to disable distorted messages, which should be able to fix this temporarily. 

Do you happen to have logs of such incidents (client-side)? There might be valuable information in them. Who knows.

**Comment by oaksvirals** [comment]
The client logs don't show anything for it unfortunately. I'll let you know if the update worked soon.

**Comment by oaksvirals** [comment]
Actually where can I download the latest nightly build?

**Comment by Ivorforce** [comment]
It's linked in the Readme - https://drone.io/github.com/Ivorforce/Psychedelicraft/files

**Comment by oaksvirals** [comment]
Works perfectly. You're amazing and thank you.
