### ISSUE TITLE
Minecraft doesn't start?

### ISSUE THREAD

**Issue by FactoryKeiks** [Ivorforce/Psychedelicraft#9]
i'll click play from the launcher and nothing will show up i've waited for awhile i even made sure it was the only mod i had and still nothing please help i miss this mod i used to play it all the time back in 1.4.2

**Comment by Ivorforce** [comment]
Make sure you have IvToolkit installed, and are running Java 7. If that doesn't help, I'm gonna need a log - either wait till it crashed, and if it doesn't, paste the console tab contents from the launcher when the game is in the frozen state.

**Comment by FactoryKeiks** [comment]
It was the IvToolkit haha i must've not known about that cause it wasn't needed before but thanks man!!!!
